mod display;
mod dns;
mod logger;
mod platform;
mod profile;
mod storage;
mod sysinfo;
mod touch;
mod web;
mod wifi;

use std::cell::RefCell;
use std::sync::{Arc, Mutex};
use std::time::Instant;

use esp_idf_hal::ledc::{config::TimerConfig, LedcDriver, LedcTimerDriver};
use esp_idf_hal::peripherals::Peripherals;
use esp_idf_hal::units::FromValueType;
use esp_idf_svc::eventloop::EspSystemEventLoop;
use esp_idf_svc::nvs::EspDefaultNvsPartition;
use esp_idf_svc::wifi::{BlockingWifi, EspWifi};
use esp_idf_sys as _;
use slint::{Image, Rgb8Pixel, SharedPixelBuffer};

use crate::platform::Esp32Platform;
use crate::touch::TouchController;

// Generated by slint-build from ui/badge.slint
slint::include_modules!();

/// Paint pixels outside a rounded rectangle with a background color.
///
/// Slint's software renderer does not clip children to `border-radius`
/// (upstream issue #4176), so we bake the rounded corners directly into
/// the RGB888 pixel buffer before handing it to Slint.
///
/// The radius is specified in pixels and applies to all four corners.
fn apply_rounded_corners(data: &mut [u8], w: u32, h: u32, radius: u32, bg: [u8; 3]) {
    let r = radius.min(w / 2).min(h / 2);
    let r_sq = (r * r) as i64;

    for y in 0..h {
        for x in 0..w {
            // Determine which corner (if any) this pixel is near
            let (dx, dy) = if x < r && y < r {
                // Top-left corner
                (r - 1 - x, r - 1 - y)
            } else if x >= w - r && y < r {
                // Top-right corner
                (x - (w - r), r - 1 - y)
            } else if x < r && y >= h - r {
                // Bottom-left corner
                (r - 1 - x, y - (h - r))
            } else if x >= w - r && y >= h - r {
                // Bottom-right corner
                (x - (w - r), y - (h - r))
            } else {
                continue; // Not in a corner region
            };

            let dist_sq = (dx as i64) * (dx as i64) + (dy as i64) * (dy as i64);
            if dist_sq > r_sq {
                let idx = ((y * w + x) * 3) as usize;
                data[idx] = bg[0];
                data[idx + 1] = bg[1];
                data[idx + 2] = bg[2];
            }
        }
    }
}

/// Apply color properties from a profile to the Slint UI.
fn apply_profile_colors(ui: &BadgeUI, p: &profile::Profile) {
    if let Some(c) = profile::parse_hex_color(&p.background_color) {
        ui.set_badge_background_color(c);
    }
    if let Some(c) = profile::parse_hex_color(&p.tagline_color) {
        ui.set_tagline_color(c);
    }
    if let Some(c) = profile::parse_hex_color(&p.tagline_background_color) {
        ui.set_tagline_background_color(c);
    }
}

fn main() -> anyhow::Result<()> {
    // Initialize dual logger (serial + ring buffer for About page)
    logger::init();
    let boot_time = Instant::now();
    log::info!("VRCBadge firmware starting");

    // Take hardware peripherals
    let peripherals = Peripherals::take()?;

    // --- Persistent storage (NVS + SPIFFS) ---
    let nvs_partition = EspDefaultNvsPartition::take()?;
    let nvs_for_storage = nvs_partition.clone(); // clone before WiFi consumes it
    let mut nvs = storage::init_nvs(nvs_for_storage)?;
    storage::init_spiffs()?;

    // --- WiFi AP + HTTP server ---
    let sys_loop = EspSystemEventLoop::take()?;
    let (wifi_driver, ap_ip) = wifi::init(peripherals.modem, sys_loop, nvs_partition)?;
    let wifi_handle: Arc<Mutex<BlockingWifi<EspWifi<'static>>>> = Arc::new(Mutex::new(wifi_driver));
    dns::start(ap_ip)?;
    let pending_background: web::SharedImageData = Arc::new(Mutex::new(None));
    let pending_avatar: web::SharedImageData = Arc::new(Mutex::new(None));
    let saved_profile = storage::load_profile(&nvs).unwrap_or_default();
    let current_profile: profile::CurrentProfile = Arc::new(Mutex::new(saved_profile.clone()));
    let pending_profile: profile::PendingProfile = Arc::new(Mutex::new(None));
    let _server = web::init(
        ap_ip,
        pending_background.clone(),
        pending_avatar.clone(),
        current_profile.clone(),
        pending_profile.clone(),
    )?;

    // --- Slint platform ---
    let esp_platform = Esp32Platform::new();
    let window = esp_platform.window();
    slint::platform::set_platform(Box::new(esp_platform))
        .map_err(|e| anyhow::anyhow!("Failed to set Slint platform: {:?}", e))?;

    // --- Display (ST7262 RGB parallel panel) ---
    // The RGB panel driver allocates a framebuffer in PSRAM and continuously
    // DMA-refreshes the display. No SPI, no manual pixel pushing.
    let (_display, framebuffer) = display::init()?;

    // --- Backlight PWM (600Hz, 8-bit, GPIO 2) ---
    // The JC8048W550 backlight is driven through a boost LED driver IC (U5).
    // GPIO 2 connects to the IC's EN pin, which accepts PWM for dimming.
    // 600Hz matches the Arduino demos for this board.
    let timer = LedcTimerDriver::new(
        peripherals.ledc.timer0,
        &TimerConfig::new()
            .frequency(600.Hz().into())
            .resolution(esp_idf_hal::ledc::Resolution::Bits8),
    )?;
    let mut backlight = LedcDriver::new(peripherals.ledc.channel0, timer, peripherals.pins.gpio2)?;
    let max_duty = backlight.get_max_duty();
    backlight.set_duty(max_duty / 2)?; // Start at 50% brightness
    log::info!("Backlight PWM initialized (GPIO 2, 600Hz, 50%)");

    // --- Touch (GT911 over I2C) ---
    let mut touch = match TouchController::new(
        peripherals.i2c0,
        peripherals.pins.gpio19.into(), // SDA
        peripherals.pins.gpio20.into(), // SCL
        peripherals.pins.gpio38.into(), // Touch RST
    ) {
        Ok(t) => Some(t),
        Err(e) => {
            log::warn!("Touch init failed (display/WiFi still active): {e}");
            None
        }
    };

    // --- Create UI ---
    let ui = BadgeUI::new().map_err(|e| anyhow::anyhow!("Failed to create UI: {:?}", e))?;

    // Set initial values from saved (or default) profile
    apply_profile_colors(&ui, &saved_profile);
    ui.set_display_name(saved_profile.display_name.into());
    ui.set_tagline(saved_profile.tagline.into());
    ui.set_twitter_handle(saved_profile.twitter_handle.into());
    ui.set_discord_handle(saved_profile.discord_handle.into());
    ui.set_battery_percent(100);
    ui.set_wifi_ip(ap_ip.to_string().into());
    ui.set_firmware_version(sysinfo::firmware_version().into());

    // Restore saved avatar from SPIFFS (216 KB @ 240x300)
    if let Some(mut rgb_data) = storage::load_image("avatar", storage::AVATAR_IMAGE_SIZE) {
        apply_rounded_corners(
            &mut rgb_data,
            storage::AVATAR_WIDTH,
            storage::AVATAR_HEIGHT,
            20,
            [0x2a, 0x2a, 0x4a],
        );
        let buffer = SharedPixelBuffer::<Rgb8Pixel>::clone_from_slice(
            &rgb_data,
            storage::AVATAR_WIDTH,
            storage::AVATAR_HEIGHT,
        );
        ui.set_avatar_image(Image::from_rgb8(buffer));
    }

    // Restore saved background from SPIFFS
    if let Some(rgb_data) = storage::load_image("background", storage::BACKGROUND_IMAGE_SIZE) {
        let buffer = SharedPixelBuffer::<Rgb8Pixel>::clone_from_slice(
            &rgb_data,
            platform::DISPLAY_WIDTH,
            platform::DISPLAY_HEIGHT,
        );
        ui.set_background_image(Image::from_rgb8(buffer));
    }

    // Wire brightness slider to backlight PWM (debounced to avoid flicker).
    // Converts 10-100% from the UI slider to 0-255 LEDC duty cycle.
    let backlight = RefCell::new(backlight);
    let last_brightness = RefCell::new(50.0_f32);
    ui.on_brightness_changed(move |percent| {
        let clamped = percent.clamp(10.0, 100.0);
        let mut last = last_brightness.borrow_mut();
        if (clamped - *last).abs() >= 2.0 {
            *last = clamped;
            let duty = (clamped / 100.0 * max_duty as f32) as u32;
            let _ = backlight.borrow_mut().set_duty(duty);
        }
    });

    // Wire virtual keyboard key dispatch.
    // When a key is tapped on the on-screen keyboard, dispatch it as a
    // KeyPressed + KeyReleased event so Slint routes it to the focused TextInput.
    {
        let weak = ui.as_weak();
        ui.global::<VirtualKeyboardHandler>()
            .on_key_pressed(move |key| {
                if let Some(ui) = weak.upgrade() {
                    ui.window()
                        .dispatch_event(slint::platform::WindowEvent::KeyPressed {
                            text: key.clone(),
                        });
                    ui.window()
                        .dispatch_event(slint::platform::WindowEvent::KeyReleased { text: key });
                }
            });
    }

    // --- Auto-connect to saved WiFi network (background, non-blocking) ---
    // Try to connect at boot if credentials are saved. On failure, continue
    // with AP-only mode and show a dimmed WiFi icon.
    let mut sta_connected = false;
    if let Some((ssid, password)) = storage::load_wifi_credentials(&nvs) {
        log::info!("Auto-connecting to saved WiFi: {ssid}");
        if let Ok(mut wifi) = wifi_handle.lock() {
            match wifi::connect_sta(&mut wifi, &ssid, &password) {
                Ok(ip) => {
                    ui.set_sta_connected(true);
                    ui.set_sta_ssid(ssid.into());
                    ui.set_sta_ip(ip.to_string().into());
                    sta_connected = true;
                }
                Err(e) => {
                    log::warn!("Auto-connect failed: {e}");
                    ui.set_sta_connected(false);
                    // Show toast: will be handled in Stage 3
                }
            }
        }
    }
    // Track whether we have saved credentials (for dimmed icon vs hidden)
    let has_wifi_credentials = storage::load_wifi_credentials(&nvs).is_some();
    ui.set_has_wifi_credentials(has_wifi_credentials || sta_connected);

    log::info!("Boot complete, entering main loop");

    // --- Main event loop ---
    let mut loop_count: u32 = 0;
    loop {
        // 1. Process Slint timers and animations
        slint::platform::update_timers_and_animations();

        // 2. Poll touch input -> dispatch events to Slint
        if let Some(ref mut touch) = touch {
            touch.poll(&window);
        }

        // 3. Poll for updates (~every 2 seconds at 16ms sleep = 125 iterations)
        loop_count = loop_count.wrapping_add(1);
        if loop_count % 125 == 0 {
            // WiFi AP client count
            let clients = wifi::connected_clients() as i32;
            ui.set_wifi_clients(clients);

            // WiFi STA connection status
            if let Ok(wifi) = wifi_handle.try_lock() {
                match wifi::sta_status(&wifi) {
                    wifi::StaStatus::Connected { ssid, ip } => {
                        if !sta_connected {
                            log::info!("WiFi STA connected: {ssid} ({ip})");
                            sta_connected = true;
                        }
                        ui.set_sta_connected(true);
                        ui.set_sta_ssid(ssid.into());
                        ui.set_sta_ip(ip.to_string().into());
                    }
                    wifi::StaStatus::Disconnected => {
                        if sta_connected {
                            log::warn!("WiFi STA disconnected");
                            sta_connected = false;
                        }
                        ui.set_sta_connected(false);
                    }
                }
            }

            // About page: system info + logs
            ui.set_about_uptime(sysinfo::uptime_string(&boot_time).into());
            ui.set_about_heap(format!("{} KB", sysinfo::free_heap_kb()).into());
            ui.set_about_psram(format!("{} KB", sysinfo::free_psram_kb()).into());
            ui.set_log_text(logger::snapshot().into());

            // Check for profile update from web
            if let Ok(mut pending) = pending_profile.try_lock() {
                if let Some(new_profile) = pending.take() {
                    ui.set_display_name(new_profile.display_name.clone().into());
                    ui.set_tagline(new_profile.tagline.clone().into());
                    ui.set_twitter_handle(new_profile.twitter_handle.clone().into());
                    ui.set_discord_handle(new_profile.discord_handle.clone().into());
                    apply_profile_colors(&ui, &new_profile);
                    // Update current profile for future GET /api/profile requests
                    if let Ok(mut current) = current_profile.try_lock() {
                        *current = new_profile.clone();
                    }
                    storage::save_profile(&mut nvs, &new_profile);
                    log::info!("Badge profile updated");
                }
            }

            // Check for new avatar image from HTTP upload
            if let Ok(mut pending) = pending_avatar.try_lock() {
                if let Some(mut rgb_data) = pending.take() {
                    // Save raw image first (without rounded corners) so reload
                    // works if border-radius changes in the future.
                    storage::save_image("avatar", &rgb_data);
                    apply_rounded_corners(
                        &mut rgb_data,
                        storage::AVATAR_WIDTH,
                        storage::AVATAR_HEIGHT,
                        20,
                        [0x2a, 0x2a, 0x4a],
                    );
                    let buffer = SharedPixelBuffer::<Rgb8Pixel>::clone_from_slice(
                        &rgb_data,
                        storage::AVATAR_WIDTH,
                        storage::AVATAR_HEIGHT,
                    );
                    ui.set_avatar_image(Image::from_rgb8(buffer));
                    log::info!("Avatar image updated");
                }
            }

            // Check for new background image from HTTP upload
            // An empty vec signals "clear the background image".
            if let Ok(mut pending) = pending_background.try_lock() {
                if let Some(rgb_data) = pending.take() {
                    if rgb_data.is_empty() {
                        // Clear: reset to solid color, delete saved image
                        ui.set_background_image(Image::default());
                        storage::delete_image("background");
                        log::info!("Background image cleared");
                    } else {
                        let buffer = SharedPixelBuffer::<Rgb8Pixel>::clone_from_slice(
                            &rgb_data,
                            platform::DISPLAY_WIDTH,
                            platform::DISPLAY_HEIGHT,
                        );
                        ui.set_background_image(Image::from_rgb8(buffer));
                        storage::save_image("background", &rgb_data);
                        log::info!("Background image updated");
                    }
                }
            }
        }

        // 4. Render into framebuffer and flush cache for dirty regions
        // The RGB panel hardware continuously DMA-refreshes from the framebuffer.
        // We just need to ensure our writes are visible to the DMA controller.
        window.draw_if_needed(|renderer| {
            let region = renderer.render(framebuffer, platform::DISPLAY_WIDTH as usize);
            display::flush_dirty_region(framebuffer, region);
        });

        // 5. Sleep until next event needed
        if !window.has_active_animations() {
            if let Some(duration) = slint::platform::duration_until_next_timer_update() {
                // Sleep for at most the duration, but wake periodically for touch polling
                let sleep_ms = duration.as_millis().min(16) as u32; // Cap at ~60fps for touch
                esp_idf_hal::delay::FreeRtos::delay_ms(sleep_ms);
            } else {
                // No timers pending -- sleep briefly for touch responsiveness
                esp_idf_hal::delay::FreeRtos::delay_ms(16);
            }
        }
    }
}
